architecture: replication

auth:
  rootPassword: secret-root-pass
  database: my-app-db
  username: my-user
  password: my-pass

volumePermissions:
  enabled: true

primary:
  persistence:
    enabled: false

secondary:
  replicaCount: 2
  persistence:
    enabled: false

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: my-kube-prometheus-stack
  service:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9104"  # Default port for MySQL metrics exporter



# helm repo add bitnami https://charts.bitnami.com/bitnami
# helm install mysql-release bitnami/mysql -f mysql-chart-values-eks.yaml